services:
  terminal:
    build:
      context: tools/helmfile-job-runner
    volumes:
      - ~/.kube:/root/.kube:ro
      - ~/.aws:/root/.aws:ro
      - .:/var/workspace:rw
    environment:
      AWS_PROFILE: $AWS_PROFILE
    working_dir: /var/workspace
